services:
  postgres:
    image: postgres:15
    container_name: apollo_vehicles_db
    environment:
      POSTGRES_DB: vehicles_db
      POSTGRES_USER: vehicles_user
      POSTGRES_PASSWORD: apollo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vehicles_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

